-- Reset do modelo do coletor da extensao Oddzone.
-- Objetivo: foco em odds de futebol + dados de conta + apostas do usuario.
-- Substitui modelo anterior (collector_installations, account_profiles, bets,
-- odds_snapshots, site_sessions, user_consents, consent_terms, collector_failures,
-- extension_events).

create extension if not exists pgcrypto;
create extension if not exists pg_cron;

-- 1. Limpar job antigo de TTL, se existir
do $$
declare
  existing_job_id bigint;
begin
  select jobid into existing_job_id
  from cron.job
  where jobname in (
    'collector_odds_expiry_every_5_minutes',
    'ext_football_odds_expiry_every_5_minutes'
  )
  limit 1;

  if existing_job_id is not null then
    perform cron.unschedule(existing_job_id);
  end if;
exception
  when undefined_table then
    null;
end;
$$;

-- 2. Drop do modelo anterior (idempotente)
drop function if exists private.cleanup_expired_odds();
drop table if exists public.collector_failures cascade;
drop table if exists public.odds_snapshots cascade;
drop table if exists public.bets cascade;
drop table if exists public.account_profiles cascade;
drop table if exists public.site_sessions cascade;
drop table if exists public.user_consents cascade;
drop table if exists public.consent_terms cascade;
drop table if exists public.collector_installations cascade;
drop table if exists public.extension_events cascade;

-- 3. Modelo novo (3 tabelas objetivas)

-- 3.1 Instalacao + perfil do usuario capturado da casa de aposta
create table public.ext_users (
  install_id text primary key,
  bookmaker text not null,
  email text,
  display_name text,
  balance_cents bigint,
  currency text,
  extension_version text not null,
  consent_accepted_at timestamptz,
  consent_term_version text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index ext_users_bookmaker_idx on public.ext_users (bookmaker);
create index ext_users_email_idx on public.ext_users (email) where email is not null;

-- 3.2 Odds de futebol capturadas (TTL 1h)
create table public.ext_football_odds (
  id bigint generated by default as identity primary key,
  install_id text not null references public.ext_users(install_id) on delete cascade,
  bookmaker text not null,
  league text,
  event_name text,
  home_team text,
  away_team text,
  market text,
  selection text,
  odd_value numeric(10,4) not null,
  confidence_score smallint not null default 0,
  page_url text,
  captured_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '1 hour')
);

create index ext_football_odds_install_idx on public.ext_football_odds (install_id, captured_at desc);
create index ext_football_odds_event_idx on public.ext_football_odds (bookmaker, event_name, market);
create index ext_football_odds_expires_idx on public.ext_football_odds (expires_at);

-- 3.3 Apostas realizadas pelo usuario
create table public.ext_user_bets (
  id bigint generated by default as identity primary key,
  install_id text not null references public.ext_users(install_id) on delete cascade,
  bookmaker text not null,
  betslip_id text,
  league text,
  event_name text,
  market text,
  selection text,
  stake_cents bigint,
  odd_value numeric(10,4),
  potential_return_cents bigint,
  status text,
  placed_at timestamptz,
  captured_at timestamptz not null default now()
);

create index ext_user_bets_install_idx on public.ext_user_bets (install_id, captured_at desc);
create unique index ext_user_bets_betslip_uidx on public.ext_user_bets (install_id, bookmaker, betslip_id)
  where betslip_id is not null;

-- 4. RLS: tabelas são internas, gravadas apenas pelo backend com service role
alter table public.ext_users enable row level security;
alter table public.ext_football_odds enable row level security;
alter table public.ext_user_bets enable row level security;

revoke all on table public.ext_users from anon, authenticated;
revoke all on table public.ext_football_odds from anon, authenticated;
revoke all on table public.ext_user_bets from anon, authenticated;

-- 5. Job de TTL de odds (executa a cada 5 minutos)
create schema if not exists private;

create or replace function private.cleanup_expired_football_odds()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  removed_count integer;
begin
  delete from public.ext_football_odds
  where expires_at <= now();

  get diagnostics removed_count = row_count;
  return removed_count;
end;
$$;

do $$
begin
  perform cron.schedule(
    'ext_football_odds_expiry_every_5_minutes',
    '*/5 * * * *',
    'select private.cleanup_expired_football_odds();'
  );
exception
  when undefined_table then
    raise notice 'pg_cron nao disponivel. Configure um job externo periodico para chamar private.cleanup_expired_football_odds().';
end;
$$;
