create table if not exists public.extension_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null check (event_type in ('startup', 'install')),
  extension_version text not null,
  latest_known_version text,
  update_available boolean
);

alter table public.extension_events enable row level security;

grant insert on table public.extension_events to anon, authenticated;
revoke select, update, delete on table public.extension_events from anon, authenticated;

drop policy if exists "allow_anon_insert_extension_events" on public.extension_events;
create policy "allow_anon_insert_extension_events"
on public.extension_events
for insert
to anon
with check (
  event_type in ('startup', 'install')
);

drop policy if exists "allow_auth_insert_extension_events" on public.extension_events;
create policy "allow_auth_insert_extension_events"
on public.extension_events
for insert
to authenticated
with check (
  event_type in ('startup', 'install')
);
