create extension if not exists pgcrypto;
create extension if not exists pg_cron;

create table if not exists public.collector_installations (
  installation_id text primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  latest_extension_version text not null
);

create table if not exists public.consent_terms (
  term_version text primary key,
  term_text text not null,
  term_hash text not null,
  published_at timestamptz not null default now()
);

create table if not exists public.user_consents (
  id bigint generated by default as identity primary key,
  installation_id text not null references public.collector_installations(installation_id) on delete cascade,
  term_version text not null references public.consent_terms(term_version),
  term_hash text,
  accepted_at timestamptz not null,
  source_url text,
  statement text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.site_sessions (
  id uuid primary key default gen_random_uuid(),
  installation_id text not null references public.collector_installations(installation_id) on delete cascade,
  site_domain text not null check (site_domain like '%.bet.br'),
  page_url text,
  page_title text,
  visited_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.account_profiles (
  id bigint generated by default as identity primary key,
  installation_id text not null references public.collector_installations(installation_id) on delete cascade,
  site_domain text not null check (site_domain like '%.bet.br'),
  captured_at timestamptz not null,
  username text,
  balance_cents bigint,
  balance_currency text,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.bets (
  id bigint generated by default as identity primary key,
  installation_id text not null references public.collector_installations(installation_id) on delete cascade,
  site_domain text not null check (site_domain like '%.bet.br'),
  captured_at timestamptz not null,
  betslip_id text,
  market text,
  selection text,
  stake_cents bigint,
  odd_value numeric(10,4),
  status text,
  placed_at timestamptz,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.odds_snapshots (
  id bigint generated by default as identity primary key,
  installation_id text not null references public.collector_installations(installation_id) on delete cascade,
  site_domain text not null check (site_domain like '%.bet.br'),
  captured_at timestamptz not null,
  expires_at timestamptz not null default (now() + interval '1 hour'),
  event_name text,
  market text,
  selection text,
  odd_value numeric(10,4),
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.collector_failures (
  id bigint generated by default as identity primary key,
  installation_id text references public.collector_installations(installation_id) on delete set null,
  site_domain text,
  source_url text,
  error_code text not null,
  error_message text not null,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_user_consents_installation_id on public.user_consents (installation_id);
create index if not exists idx_site_sessions_installation_id on public.site_sessions (installation_id, visited_at desc);
create index if not exists idx_account_profiles_installation_id on public.account_profiles (installation_id, captured_at desc);
create index if not exists idx_bets_installation_id on public.bets (installation_id, captured_at desc);
create index if not exists idx_odds_snapshots_expires_at on public.odds_snapshots (expires_at);
create index if not exists idx_odds_snapshots_installation on public.odds_snapshots (installation_id, captured_at desc);
create index if not exists idx_collector_failures_installation on public.collector_failures (installation_id, created_at desc);

insert into public.consent_terms (term_version, term_text, term_hash)
values (
  '2026-05-15-v1',
  'Ao aceitar este termo, o usuario autoriza a extensao Oddzone a coletar dados em dominios .bet.br, incluindo odds ao vivo, informacoes de conta e apostas exibidas em tela.',
  md5('2026-05-15-v1:oddzone_collector')
)
on conflict (term_version) do nothing;

alter table public.collector_installations enable row level security;
alter table public.consent_terms enable row level security;
alter table public.user_consents enable row level security;
alter table public.site_sessions enable row level security;
alter table public.account_profiles enable row level security;
alter table public.bets enable row level security;
alter table public.odds_snapshots enable row level security;
alter table public.collector_failures enable row level security;

revoke all on table public.collector_installations from anon, authenticated;
revoke all on table public.consent_terms from anon, authenticated;
revoke all on table public.user_consents from anon, authenticated;
revoke all on table public.site_sessions from anon, authenticated;
revoke all on table public.account_profiles from anon, authenticated;
revoke all on table public.bets from anon, authenticated;
revoke all on table public.odds_snapshots from anon, authenticated;
revoke all on table public.collector_failures from anon, authenticated;

create schema if not exists private;

create or replace function private.cleanup_expired_odds()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  removed_count integer;
begin
  delete from public.odds_snapshots
  where expires_at <= now();

  get diagnostics removed_count = row_count;
  return removed_count;
end;
$$;

do $$
declare
  existing_job_id bigint;
begin
  select jobid into existing_job_id
  from cron.job
  where jobname = 'collector_odds_expiry_every_5_minutes'
  limit 1;

  if existing_job_id is not null then
    perform cron.unschedule(existing_job_id);
  end if;

  perform cron.schedule(
    'collector_odds_expiry_every_5_minutes',
    '*/5 * * * *',
    'select private.cleanup_expired_odds();'
  );
exception
  when undefined_table then
    raise notice 'pg_cron nao disponivel neste ambiente. Configure um job externo para chamar private.cleanup_expired_odds() periodicamente.';
end;
$$;
